services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    volumes:
      - pgdata:/var/lib/postgresql/data


  app:
    image: 13347532fgh321/mini-crm:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
    ports:
      - "8000:8000"
    command: bash -c "alembic revision --autogenerate &&
      alembic upgrade head &&
      echo '✅ Migrations applied. Waiting for DB to be ready...' &&
      sleep 2 &&
      python init_data.py &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./:/code


volumes:
  pgdata: